# Generated by Django 5.0.2 on 2025-03-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminactivity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Admin Activities'},
        ),
        migrations.AlterField(
            model_name='adminactivity',
            name='action',
            field=models.CharField(default='unknown_action', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminactivity',
            name='details',
            field=models.TextField(default='No details provided'),
        ),
        migrations.AlterField(
            model_name='adminactivity',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='dashboardsetting',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dashboardsetting',
            name='value',
            field=models.TextField(default='{}'),
        ),
    ]
